name: 'Deploy lighthouse report'
description: 'Deploy lighthouse report to Vercel'
inputs:
  vercel_token:
    description: 'Vercel Token'
    required: true
  github_token:
    description: 'Github Token'
    required: true
runs:
  using: "composite"
  steps: 
    - shell: bash
      run: |
        vercel -t ${{ inputs.vercel_token }} deploy ./report/https*.html | tee vercel-now.log
        TARGET_URL=`tail -n1 vercel-now.log`
        curl -X POST https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.client_payload.LAST_COMMIT_SHA }} \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -d "{
            \"state\": \"success\",
            \"target_url\": \"${TARGET_URL}\",
            \"description\": \"Lighthouse report\",
            \"context\": \"lighthouse-report\"
          }"
      
